include: package:flutter_lints/flutter.yaml

linter:
  rules:
  
    avoid_classes_with_only_static_members: false
    directives_ordering: true
    flutter_style_todos: true
    no_adjacent_strings_in_list: true
    parameter_assignments: true
    prefer_relative_imports: true
    prefer_asserts_with_message: true
    prefer_final_locals: true
    prefer_single_quotes: true
    prefer_typing_uninitialized_variables: true
    test_types_in_equals: true
    unnecessary_null_aware_assignments: true