// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKzoUHBDU7rhdO8XdGloMHb4O7F2i__8E',
    appId: '1:746530763459:android:eb146682bc42ecc601a876',
    messagingSenderId: '746530763459',
    projectId: 'dragonfood-4583f',
    storageBucket: 'dragonfood-4583f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU1ldVIQWArjp73Rb3Z5VB7kfqJAKfpjY',
    appId: '1:746530763459:ios:7d329bc8a75ce82101a876',
    messagingSenderId: '746530763459',
    projectId: 'dragonfood-4583f',
    storageBucket: 'dragonfood-4583f.appspot.com',
    iosClientId: '746530763459-b1r4uhs723cocngbrv9pnmiddgftrhpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dragonFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU1ldVIQWArjp73Rb3Z5VB7kfqJAKfpjY',
    appId: '1:746530763459:ios:7d329bc8a75ce82101a876',
    messagingSenderId: '746530763459',
    projectId: 'dragonfood-4583f',
    storageBucket: 'dragonfood-4583f.appspot.com',
    iosClientId: '746530763459-b1r4uhs723cocngbrv9pnmiddgftrhpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dragonFood',
  );
}
